OPENAI_API_KEY = "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"
NEWS_API_KEY = "7bdee1423c924023b081298e1edc98d1"


